name: Deploy MultiDocker

on:
  push:
    branches:
      - main  # Change this if your default branch is 'master' or something else

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Run React client tests
        run: |
          docker build -t fatihidris/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true fatihidris/react-test npm test

      - name: Build Docker images
        run: |
          docker build -t fatihidris/multi-client ./client
          docker build -t fatihidris/multi-nginx ./nginx
          docker build -t fatihidris/multi-server ./server
          docker build -t fatihidris/multi-worker ./worker

      - name: Push Docker images to DockerHub
        run: |
          docker push fatihidris/multi-client
          docker push fatihidris/multi-nginx
          docker push fatihidris/multi-server
          docker push fatihidris/multi-worker

      - name: Check required deployment files
        run: |
          echo "==== LS ===="
          ls -al
          echo "==== Dockerrun.aws.json ===="
          cat Dockerrun.aws.json
          echo "==== docker-compose.yml ===="
          cat docker-compose.yml

      - name: Generate deployment package (only Dockerrun and Compose)
        run: zip deploy.zip Dockerrun.aws.json docker-compose.yml

      - name: Check contents of deploy.zip
        run: unzip -l deploy.zip

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-266097584661
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
