name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t fatihidris/react-test-up -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true fatihidris/react-test-up npm test

      - run: docker build -t fatihidris/multi-client-up ./client
      - run: docker build -t fatihidris/multi-nginx-up ./nginx
      - run: docker build -t fatihidris/multi-server-up ./server
      - run: docker build -t fatihidris/multi-worker-up ./worker

      - run: docker push fatihidris/multi-client-up
      - run: docker push fatihidris/multi-nginx-up
      - run: docker push fatihidris/multi-server-up
      - run: docker push fatihidris/multi-worker-up

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: fatihidris/beanstalk-deploy@v20
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-docker
      #     environment_name: Multi-docker-env
      #     existing_bucket_name: elasticbeanstalk-ap-southeast-1-923445559289
      #     region: ap-southeast-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
